// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: alerts.sql

package sqlc

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createAlert = `-- name: CreateAlert :exec
INSERT INTO alerts (
    id, created_by, risk_type_id, risk_topic_id, message,
    latitude, longitude, province, municipality, neighborhood, address,
    radius_meters, severity, expires_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
`

type CreateAlertParams struct {
	ID           uuid.UUID      `json:"id"`
	CreatedBy    uuid.NullUUID  `json:"created_by"`
	RiskTypeID   uuid.UUID      `json:"risk_type_id"`
	RiskTopicID  uuid.NullUUID  `json:"risk_topic_id"`
	Message      string         `json:"message"`
	Latitude     float64        `json:"latitude"`
	Longitude    float64        `json:"longitude"`
	Province     sql.NullString `json:"province"`
	Municipality sql.NullString `json:"municipality"`
	Neighborhood sql.NullString `json:"neighborhood"`
	Address      sql.NullString `json:"address"`
	RadiusMeters int32          `json:"radius_meters"`
	Severity     interface{}    `json:"severity"`
	ExpiresAt    sql.NullTime   `json:"expires_at"`
}

func (q *Queries) CreateAlert(ctx context.Context, arg CreateAlertParams) error {
	_, err := q.db.ExecContext(ctx, createAlert,
		arg.ID,
		arg.CreatedBy,
		arg.RiskTypeID,
		arg.RiskTopicID,
		arg.Message,
		arg.Latitude,
		arg.Longitude,
		arg.Province,
		arg.Municipality,
		arg.Neighborhood,
		arg.Address,
		arg.RadiusMeters,
		arg.Severity,
		arg.ExpiresAt,
	)
	return err
}

const expireAlert = `-- name: ExpireAlert :exec
UPDATE alerts
SET status = 'expired'
WHERE id = $1
`

func (q *Queries) ExpireAlert(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, expireAlert, id)
	return err
}

const listActiveAlerts = `-- name: ListActiveAlerts :many
SELECT id, created_by, risk_type_id, risk_topic_id, message, latitude, longitude, province, municipality, neighborhood, address, radius_meters, severity, status, created_at, expires_at, resolved_at FROM alerts
WHERE status = 'active' AND (expires_at IS NULL OR expires_at > NOW())
ORDER BY created_at DESC
`

func (q *Queries) ListActiveAlerts(ctx context.Context) ([]Alert, error) {
	rows, err := q.db.QueryContext(ctx, listActiveAlerts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Alert{}
	for rows.Next() {
		var i Alert
		if err := rows.Scan(
			&i.ID,
			&i.CreatedBy,
			&i.RiskTypeID,
			&i.RiskTopicID,
			&i.Message,
			&i.Latitude,
			&i.Longitude,
			&i.Province,
			&i.Municipality,
			&i.Neighborhood,
			&i.Address,
			&i.RadiusMeters,
			&i.Severity,
			&i.Status,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.ResolvedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveAlert = `-- name: ResolveAlert :exec
UPDATE alerts
SET status = 'resolved', resolved_at = NOW()
WHERE id = $1
`

func (q *Queries) ResolveAlert(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, resolveAlert, id)
	return err
}
