// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: alert_notifications.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const countUserUnreadNotifications = `-- name: CountUserUnreadNotifications :one
SELECT COUNT(*) FROM notifications
WHERE user_id = $1 AND seen_at IS NULL
`

func (q *Queries) CountUserUnreadNotifications(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUserUnreadNotifications, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAlertNotification = `-- name: CreateAlertNotification :exec
INSERT INTO notifications (type, reference_id, user_id) VALUES ($1, $2, $3)
ON CONFLICT (type, reference_id, user_id) DO NOTHING
`

type CreateAlertNotificationParams struct {
	Type        NotificationType `json:"type"`
	ReferenceID uuid.UUID        `json:"reference_id"`
	UserID      uuid.UUID        `json:"user_id"`
}

func (q *Queries) CreateAlertNotification(ctx context.Context, arg CreateAlertNotificationParams) error {
	_, err := q.db.ExecContext(ctx, createAlertNotification, arg.Type, arg.ReferenceID, arg.UserID)
	return err
}

const listUserNotifications = `-- name: ListUserNotifications :many
SELECT id, type, reference_id, user_id, sent_at, seen_at FROM notifications
WHERE user_id = $1
ORDER BY sent_at DESC
LIMIT $2 OFFSET $3
`

type ListUserNotificationsParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

func (q *Queries) ListUserNotifications(ctx context.Context, arg ListUserNotificationsParams) ([]Notification, error) {
	rows, err := q.db.QueryContext(ctx, listUserNotifications, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Notification{}
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.ReferenceID,
			&i.UserID,
			&i.SentAt,
			&i.SeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAlertSeen = `-- name: MarkAlertSeen :exec
UPDATE notifications
SET seen_at = NOW(),
    updated_at = NOW()
WHERE reference_id = $1 AND user_id = $2
`

type MarkAlertSeenParams struct {
	ReferenceID uuid.UUID `json:"reference_id"`
	UserID      uuid.UUID `json:"user_id"`
}

func (q *Queries) MarkAlertSeen(ctx context.Context, arg MarkAlertSeenParams) error {
	_, err := q.db.ExecContext(ctx, markAlertSeen, arg.ReferenceID, arg.UserID)
	return err
}
