// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: emergency_contacts.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countPriorityEmergencyContactsByUserID = `-- name: CountPriorityEmergencyContactsByUserID :one
SELECT COUNT(*) FROM emergency_contacts WHERE user_id = $1 AND is_priority = true
`

func (q *Queries) CountPriorityEmergencyContactsByUserID(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPriorityEmergencyContactsByUserID, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createEmergencyContact = `-- name: CreateEmergencyContact :exec
INSERT INTO emergency_contacts (id, user_id, name, phone, relation, is_priority, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type CreateEmergencyContactParams struct {
	ID         uuid.UUID `json:"id"`
	UserID     uuid.UUID `json:"user_id"`
	Name       string    `json:"name"`
	Phone      string    `json:"phone"`
	Relation   string    `json:"relation"`
	IsPriority bool      `json:"is_priority"`
	CreatedAt  time.Time `json:"created_at"`
	UpdatedAt  time.Time `json:"updated_at"`
}

func (q *Queries) CreateEmergencyContact(ctx context.Context, arg CreateEmergencyContactParams) error {
	_, err := q.db.ExecContext(ctx, createEmergencyContact,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Phone,
		arg.Relation,
		arg.IsPriority,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteEmergencyContact = `-- name: DeleteEmergencyContact :exec
DELETE FROM emergency_contacts WHERE id = $1
`

func (q *Queries) DeleteEmergencyContact(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteEmergencyContact, id)
	return err
}

const deleteEmergencyContactByUserIDAndID = `-- name: DeleteEmergencyContactByUserIDAndID :exec
DELETE FROM emergency_contacts WHERE user_id = $1 AND id = $2
`

type DeleteEmergencyContactByUserIDAndIDParams struct {
	UserID uuid.UUID `json:"user_id"`
	ID     uuid.UUID `json:"id"`
}

func (q *Queries) DeleteEmergencyContactByUserIDAndID(ctx context.Context, arg DeleteEmergencyContactByUserIDAndIDParams) error {
	_, err := q.db.ExecContext(ctx, deleteEmergencyContactByUserIDAndID, arg.UserID, arg.ID)
	return err
}

const getEmergencyContactByID = `-- name: GetEmergencyContactByID :one
SELECT id, user_id, name, phone, relation, is_priority, created_at, updated_at FROM emergency_contacts WHERE id = $1 LIMIT 1
`

func (q *Queries) GetEmergencyContactByID(ctx context.Context, id uuid.UUID) (EmergencyContact, error) {
	row := q.db.QueryRowContext(ctx, getEmergencyContactByID, id)
	var i EmergencyContact
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Phone,
		&i.Relation,
		&i.IsPriority,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEmergencyContactByUserIDAndID = `-- name: GetEmergencyContactByUserIDAndID :one
SELECT id, user_id, name, phone, relation, is_priority, created_at, updated_at FROM emergency_contacts WHERE user_id = $1 AND id = $2 LIMIT 1
`

type GetEmergencyContactByUserIDAndIDParams struct {
	UserID uuid.UUID `json:"user_id"`
	ID     uuid.UUID `json:"id"`
}

func (q *Queries) GetEmergencyContactByUserIDAndID(ctx context.Context, arg GetEmergencyContactByUserIDAndIDParams) (EmergencyContact, error) {
	row := q.db.QueryRowContext(ctx, getEmergencyContactByUserIDAndID, arg.UserID, arg.ID)
	var i EmergencyContact
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Phone,
		&i.Relation,
		&i.IsPriority,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEmergencyContactsByUserID = `-- name: GetEmergencyContactsByUserID :many
SELECT id, user_id, name, phone, relation, is_priority, created_at, updated_at FROM emergency_contacts WHERE user_id = $1 ORDER BY is_priority DESC, created_at ASC
`

func (q *Queries) GetEmergencyContactsByUserID(ctx context.Context, userID uuid.UUID) ([]EmergencyContact, error) {
	rows, err := q.db.QueryContext(ctx, getEmergencyContactsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EmergencyContact{}
	for rows.Next() {
		var i EmergencyContact
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Phone,
			&i.Relation,
			&i.IsPriority,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPriorityEmergencyContactsByUserID = `-- name: GetPriorityEmergencyContactsByUserID :many
SELECT id, user_id, name, phone, relation, is_priority, created_at, updated_at FROM emergency_contacts WHERE user_id = $1 AND is_priority = true ORDER BY created_at ASC
`

func (q *Queries) GetPriorityEmergencyContactsByUserID(ctx context.Context, userID uuid.UUID) ([]EmergencyContact, error) {
	rows, err := q.db.QueryContext(ctx, getPriorityEmergencyContactsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EmergencyContact{}
	for rows.Next() {
		var i EmergencyContact
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Phone,
			&i.Relation,
			&i.IsPriority,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEmergencyContact = `-- name: UpdateEmergencyContact :exec
UPDATE emergency_contacts
SET name = $2, phone = $3, relation = $4, is_priority = $5, updated_at = $6
WHERE id = $1
`

type UpdateEmergencyContactParams struct {
	ID         uuid.UUID `json:"id"`
	Name       string    `json:"name"`
	Phone      string    `json:"phone"`
	Relation   string    `json:"relation"`
	IsPriority bool      `json:"is_priority"`
	UpdatedAt  time.Time `json:"updated_at"`
}

func (q *Queries) UpdateEmergencyContact(ctx context.Context, arg UpdateEmergencyContactParams) error {
	_, err := q.db.ExecContext(ctx, updateEmergencyContact,
		arg.ID,
		arg.Name,
		arg.Phone,
		arg.Relation,
		arg.IsPriority,
		arg.UpdatedAt,
	)
	return err
}
