// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: entities.sql

package sqlc

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createEntity = `-- name: CreateEntity :one
INSERT INTO entities (
    name, entity_type, province, municipality, latitude, longitude, contact_email, contact_phone
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, name, entity_type, province, municipality, latitude, longitude, contact_email, contact_phone, created_at
`

type CreateEntityParams struct {
	Name         string          `json:"name"`
	EntityType   interface{}     `json:"entity_type"`
	Province     sql.NullString  `json:"province"`
	Municipality sql.NullString  `json:"municipality"`
	Latitude     sql.NullFloat64 `json:"latitude"`
	Longitude    sql.NullFloat64 `json:"longitude"`
	ContactEmail sql.NullString  `json:"contact_email"`
	ContactPhone sql.NullString  `json:"contact_phone"`
}

func (q *Queries) CreateEntity(ctx context.Context, arg CreateEntityParams) (Entity, error) {
	row := q.db.QueryRowContext(ctx, createEntity,
		arg.Name,
		arg.EntityType,
		arg.Province,
		arg.Municipality,
		arg.Latitude,
		arg.Longitude,
		arg.ContactEmail,
		arg.ContactPhone,
	)
	var i Entity
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.EntityType,
		&i.Province,
		&i.Municipality,
		&i.Latitude,
		&i.Longitude,
		&i.ContactEmail,
		&i.ContactPhone,
		&i.CreatedAt,
	)
	return i, err
}

const deleteEntity = `-- name: DeleteEntity :exec
DELETE FROM entities WHERE id = $1
`

func (q *Queries) DeleteEntity(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteEntity, id)
	return err
}

const getEntitiesByType = `-- name: GetEntitiesByType :many
SELECT id, name, entity_type, province, municipality, latitude, longitude, contact_email, contact_phone, created_at FROM entities WHERE entity_type = $1 ORDER BY created_at DESC
`

func (q *Queries) GetEntitiesByType(ctx context.Context, entityType interface{}) ([]Entity, error) {
	rows, err := q.db.QueryContext(ctx, getEntitiesByType, entityType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Entity{}
	for rows.Next() {
		var i Entity
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.EntityType,
			&i.Province,
			&i.Municipality,
			&i.Latitude,
			&i.Longitude,
			&i.ContactEmail,
			&i.ContactPhone,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEntities = `-- name: ListEntities :many
SELECT id, name, entity_type, province, municipality, latitude, longitude, contact_email, contact_phone, created_at FROM entities ORDER BY created_at DESC
`

func (q *Queries) ListEntities(ctx context.Context) ([]Entity, error) {
	rows, err := q.db.QueryContext(ctx, listEntities)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Entity{}
	for rows.Next() {
		var i Entity
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.EntityType,
			&i.Province,
			&i.Municipality,
			&i.Latitude,
			&i.Longitude,
			&i.ContactEmail,
			&i.ContactPhone,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
