// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package sqlc

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
)

type NotificationType string

const (
	NotificationTypeAlert  NotificationType = "alert"
	NotificationTypeReport NotificationType = "report"
)

func (e *NotificationType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = NotificationType(s)
	case string:
		*e = NotificationType(s)
	default:
		return fmt.Errorf("unsupported scan type for NotificationType: %T", src)
	}
	return nil
}

type NullNotificationType struct {
	NotificationType NotificationType `json:"notification_type"`
	Valid            bool             `json:"valid"` // Valid is true if NotificationType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullNotificationType) Scan(value interface{}) error {
	if value == nil {
		ns.NotificationType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.NotificationType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullNotificationType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.NotificationType), nil
}

type Alert struct {
	ID                 uuid.UUID      `json:"id"`
	CreatedBy          uuid.NullUUID  `json:"created_by"`
	AnonymousSessionID uuid.NullUUID  `json:"anonymous_session_id"`
	DeviceID           sql.NullString `json:"device_id"`
	RiskTypeID         uuid.UUID      `json:"risk_type_id"`
	RiskTopicID        uuid.NullUUID  `json:"risk_topic_id"`
	Message            string         `json:"message"`
	Latitude           float64        `json:"latitude"`
	Longitude          float64        `json:"longitude"`
	Province           sql.NullString `json:"province"`
	Municipality       sql.NullString `json:"municipality"`
	Neighborhood       sql.NullString `json:"neighborhood"`
	Address            sql.NullString `json:"address"`
	RadiusMeters       int32          `json:"radius_meters"`
	Severity           interface{}    `json:"severity"`
	Status             interface{}    `json:"status"`
	CreatedAt          sql.NullTime   `json:"created_at"`
	ExpiresAt          sql.NullTime   `json:"expires_at"`
	ResolvedAt         sql.NullTime   `json:"resolved_at"`
}

type AlertSubscription struct {
	ID                 uuid.UUID      `json:"id"`
	AlertID            uuid.UUID      `json:"alert_id"`
	UserID             uuid.NullUUID  `json:"user_id"`
	AnonymousSessionID uuid.NullUUID  `json:"anonymous_session_id"`
	DeviceID           sql.NullString `json:"device_id"`
	SubscribedAt       time.Time      `json:"subscribed_at"`
}

type AnonymousSession struct {
	ID                      uuid.UUID       `json:"id"`
	DeviceID                string          `json:"device_id"`
	DeviceFcmToken          sql.NullString  `json:"device_fcm_token"`
	DevicePlatform          sql.NullString  `json:"device_platform"`
	DeviceModel             sql.NullString  `json:"device_model"`
	Latitude                sql.NullFloat64 `json:"latitude"`
	Longitude               sql.NullFloat64 `json:"longitude"`
	PushNotificationEnabled sql.NullBool    `json:"push_notification_enabled"`
	SmsNotificationEnabled  sql.NullBool    `json:"sms_notification_enabled"`
	AlertRadiusMeters       sql.NullInt32   `json:"alert_radius_meters"`
	DeviceLanguage          sql.NullString  `json:"device_language"`
	LastSeen                sql.NullTime    `json:"last_seen"`
	CreatedAt               sql.NullTime    `json:"created_at"`
	UpdatedAt               sql.NullTime    `json:"updated_at"`
	MigratedToUserID        uuid.NullUUID   `json:"migrated_to_user_id"`
	MigratedAt              sql.NullTime    `json:"migrated_at"`
	IsActive                sql.NullBool    `json:"is_active"`
}

type AnonymousUserMigration struct {
	ID                       uuid.UUID      `json:"id"`
	AnonymousSessionID       uuid.UUID      `json:"anonymous_session_id"`
	DeviceID                 string         `json:"device_id"`
	UserID                   uuid.UUID      `json:"user_id"`
	AlertsMigrated           int32          `json:"alerts_migrated"`
	SubscriptionsMigrated    int32          `json:"subscriptions_migrated"`
	SettingsMigrated         bool           `json:"settings_migrated"`
	LocationSharingsMigrated int32          `json:"location_sharings_migrated"`
	MigrationType            string         `json:"migration_type"`
	StartedAt                time.Time      `json:"started_at"`
	CompletedAt              sql.NullTime   `json:"completed_at"`
	FailedAt                 sql.NullTime   `json:"failed_at"`
	ErrorMessage             sql.NullString `json:"error_message"`
}

type DeviceUserMapping struct {
	ID                 uuid.UUID    `json:"id"`
	DeviceID           string       `json:"device_id"`
	AnonymousSessionID uuid.UUID    `json:"anonymous_session_id"`
	UserID             uuid.UUID    `json:"user_id"`
	MappedAt           time.Time    `json:"mapped_at"`
	UnmappedAt         sql.NullTime `json:"unmapped_at"`
	IsActive           bool         `json:"is_active"`
}

type EmergencyContact struct {
	ID         uuid.UUID `json:"id"`
	UserID     uuid.UUID `json:"user_id"`
	Name       string    `json:"name"`
	Phone      string    `json:"phone"`
	Relation   string    `json:"relation"`
	IsPriority bool      `json:"is_priority"`
	CreatedAt  time.Time `json:"created_at"`
	UpdatedAt  time.Time `json:"updated_at"`
}

type Entity struct {
	ID           uuid.UUID       `json:"id"`
	Name         string          `json:"name"`
	EntityType   interface{}     `json:"entity_type"`
	Province     sql.NullString  `json:"province"`
	Municipality sql.NullString  `json:"municipality"`
	Latitude     sql.NullFloat64 `json:"latitude"`
	Longitude    sql.NullFloat64 `json:"longitude"`
	ContactEmail sql.NullString  `json:"contact_email"`
	ContactPhone sql.NullString  `json:"contact_phone"`
	CreatedAt    sql.NullTime    `json:"created_at"`
}

type LocationSharing struct {
	ID                 uuid.UUID      `json:"id"`
	UserID             uuid.NullUUID  `json:"user_id"`
	AnonymousSessionID uuid.NullUUID  `json:"anonymous_session_id"`
	DeviceID           sql.NullString `json:"device_id"`
	OwnerName          sql.NullString `json:"owner_name"`
	Token              string         `json:"token"`
	Latitude           float64        `json:"latitude"`
	Longitude          float64        `json:"longitude"`
	DurationMinutes    int32          `json:"duration_minutes"`
	ExpiresAt          time.Time      `json:"expires_at"`
	LastUpdatedAt      time.Time      `json:"last_updated_at"`
	IsActive           bool           `json:"is_active"`
	CreatedAt          time.Time      `json:"created_at"`
	UpdatedAt          time.Time      `json:"updated_at"`
}

type Notification struct {
	ID          uuid.UUID        `json:"id"`
	Type        NotificationType `json:"type"`
	ReferenceID uuid.UUID        `json:"reference_id"`
	UserID      uuid.UUID        `json:"user_id"`
	SentAt      sql.NullTime     `json:"sent_at"`
	SeenAt      sql.NullTime     `json:"seen_at"`
}

type Permission struct {
	ID       uuid.UUID      `json:"id"`
	Resource string         `json:"resource"`
	Action   string         `json:"action"`
	Code     sql.NullString `json:"code"`
}

type Report struct {
	ID                uuid.UUID      `json:"id"`
	UserID            uuid.UUID      `json:"user_id"`
	RiskTypeID        uuid.UUID      `json:"risk_type_id"`
	RiskTopicID       uuid.NullUUID  `json:"risk_topic_id"`
	Description       sql.NullString `json:"description"`
	Latitude          float64        `json:"latitude"`
	Longitude         float64        `json:"longitude"`
	Province          sql.NullString `json:"province"`
	Municipality      sql.NullString `json:"municipality"`
	Neighborhood      sql.NullString `json:"neighborhood"`
	Address           sql.NullString `json:"address"`
	ImageUrl          sql.NullString `json:"image_url"`
	Status            interface{}    `json:"status"`
	ReviewedBy        uuid.NullUUID  `json:"reviewed_by"`
	ResolvedAt        sql.NullTime   `json:"resolved_at"`
	VerificationCount sql.NullInt32  `json:"verification_count"`
	RejectionCount    sql.NullInt32  `json:"rejection_count"`
	ExpiresAt         sql.NullTime   `json:"expires_at"`
	IsPrivate         bool           `json:"is_private"`
	CreatedAt         sql.NullTime   `json:"created_at"`
	UpdatedAt         sql.NullTime   `json:"updated_at"`
}

type ReportVote struct {
	ID                 uuid.UUID     `json:"id"`
	ReportID           uuid.UUID     `json:"report_id"`
	UserID             uuid.NullUUID `json:"user_id"`
	AnonymousSessionID uuid.NullUUID `json:"anonymous_session_id"`
	VoteType           string        `json:"vote_type"`
	CreatedAt          sql.NullTime  `json:"created_at"`
}

type RiskTopic struct {
	ID          uuid.UUID      `json:"id"`
	RiskTypeID  uuid.UUID      `json:"risk_type_id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	IconPath    sql.NullString `json:"icon_path"`
	IsSensitive bool           `json:"is_sensitive"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
}

type RiskType struct {
	ID          uuid.UUID      `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	IconPath    sql.NullString `json:"icon_path"`
	// Controls visibility of risk types in mobile app. When false, all associated reports are also hidden.
	IsEnabled           bool          `json:"is_enabled"`
	DefaultRadiusMeters sql.NullInt32 `json:"default_radius_meters"`
	CreatedAt           sql.NullTime  `json:"created_at"`
	UpdatedAt           sql.NullTime  `json:"updated_at"`
}

type Role struct {
	ID          uuid.UUID      `json:"id"`
	Name        string         `json:"name"`
	Priority    int32          `json:"priority"`
	Description sql.NullString `json:"description"`
}

type RolePermission struct {
	RoleID       uuid.UUID `json:"role_id"`
	PermissionID uuid.UUID `json:"permission_id"`
	GrantedAt    time.Time `json:"granted_at"`
}

type User struct {
	ID                         uuid.UUID       `json:"id"`
	Name                       string          `json:"name"`
	Email                      string          `json:"email"`
	Password                   string          `json:"password"`
	Phone                      sql.NullString  `json:"phone"`
	Latitude                   sql.NullFloat64 `json:"latitude"`
	Longitude                  sql.NullFloat64 `json:"longitude"`
	AlertRadiusMeters          sql.NullInt32   `json:"alert_radius_meters"`
	EmailVerified              sql.NullBool    `json:"email_verified"`
	AccountVerified            sql.NullBool    `json:"account_verified"`
	EmailVerificationCode      sql.NullString  `json:"email_verification_code"`
	EmailVerificationExpiresAt sql.NullTime    `json:"email_verification_expires_at"`
	Nif                        sql.NullString  `json:"nif"`
	Province                   sql.NullString  `json:"province"`
	Municipality               sql.NullString  `json:"municipality"`
	Neighborhood               sql.NullString  `json:"neighborhood"`
	Address                    sql.NullString  `json:"address"`
	ZipCode                    sql.NullString  `json:"zip_code"`
	Country                    sql.NullString  `json:"country"`
	PushNotificationEnabled    sql.NullBool    `json:"push_notification_enabled"`
	SmsNotificationEnabled     sql.NullBool    `json:"sms_notification_enabled"`
	LastLogin                  sql.NullTime    `json:"last_login"`
	HomeAddressName            sql.NullString  `json:"home_address_name"`
	HomeAddressAddress         sql.NullString  `json:"home_address_address"`
	HomeAddressLat             sql.NullFloat64 `json:"home_address_lat"`
	HomeAddressLon             sql.NullFloat64 `json:"home_address_lon"`
	WorkAddressName            sql.NullString  `json:"work_address_name"`
	WorkAddressAddress         sql.NullString  `json:"work_address_address"`
	WorkAddressLat             sql.NullFloat64 `json:"work_address_lat"`
	WorkAddressLon             sql.NullFloat64 `json:"work_address_lon"`
	FailedAttempts             sql.NullInt32   `json:"failed_attempts"`
	LockedUntil                sql.NullTime    `json:"locked_until"`
	DeviceFcmToken             sql.NullString  `json:"device_fcm_token"`
	DeviceLanguage             sql.NullString  `json:"device_language"`
	TrustScore                 sql.NullInt32   `json:"trust_score"`
	ReportsSubmitted           sql.NullInt32   `json:"reports_submitted"`
	ReportsVerified            sql.NullInt32   `json:"reports_verified"`
	CreatedAt                  sql.NullTime    `json:"created_at"`
	UpdatedAt                  sql.NullTime    `json:"updated_at"`
	DeletedAt                  sql.NullTime    `json:"deleted_at"`
	LinkedDeviceID             sql.NullString  `json:"linked_device_id"`
}

type UserLocation struct {
	ID          uuid.UUID       `json:"id"`
	UserID      uuid.UUID       `json:"user_id"`
	DeviceID    sql.NullString  `json:"device_id"`
	Latitude    float64         `json:"latitude"`
	Longitude   float64         `json:"longitude"`
	Location    interface{}     `json:"location"`
	Speed       sql.NullFloat64 `json:"speed"`
	Heading     sql.NullFloat64 `json:"heading"`
	AvatarID    int32           `json:"avatar_id"`
	Color       string          `json:"color"`
	IsAnonymous sql.NullBool    `json:"is_anonymous"`
	LastUpdate  sql.NullTime    `json:"last_update"`
	CreatedAt   sql.NullTime    `json:"created_at"`
}

type UserRole struct {
	ID         uuid.UUID    `json:"id"`
	UserID     uuid.UUID    `json:"user_id"`
	RoleID     uuid.UUID    `json:"role_id"`
	AssignedAt sql.NullTime `json:"assigned_at"`
}

type UserSafetySetting struct {
	ID                           uuid.UUID      `json:"id"`
	UserID                       uuid.NullUUID  `json:"user_id"`
	AnonymousSessionID           uuid.NullUUID  `json:"anonymous_session_id"`
	DeviceID                     sql.NullString `json:"device_id"`
	NotificationsEnabled         sql.NullBool   `json:"notifications_enabled"`
	NotificationAlertTypes       []string       `json:"notification_alert_types"`
	NotificationAlertRadiusMins  sql.NullInt32  `json:"notification_alert_radius_mins"`
	NotificationReportTypes      []string       `json:"notification_report_types"`
	NotificationReportRadiusMins sql.NullInt32  `json:"notification_report_radius_mins"`
	LocationSharingEnabled       sql.NullBool   `json:"location_sharing_enabled"`
	LocationHistoryEnabled       sql.NullBool   `json:"location_history_enabled"`
	ProfileVisibility            sql.NullString `json:"profile_visibility"`
	AnonymousReports             sql.NullBool   `json:"anonymous_reports"`
	ShowOnlineStatus             sql.NullBool   `json:"show_online_status"`
	AutoAlertsEnabled            sql.NullBool   `json:"auto_alerts_enabled"`
	DangerZonesEnabled           sql.NullBool   `json:"danger_zones_enabled"`
	TimeBasedAlertsEnabled       sql.NullBool   `json:"time_based_alerts_enabled"`
	HighRiskStartTime            sql.NullTime   `json:"high_risk_start_time"`
	HighRiskEndTime              sql.NullTime   `json:"high_risk_end_time"`
	NightModeEnabled             sql.NullBool   `json:"night_mode_enabled"`
	NightModeStartTime           sql.NullTime   `json:"night_mode_start_time"`
	NightModeEndTime             sql.NullTime   `json:"night_mode_end_time"`
	CreatedAt                    sql.NullTime   `json:"created_at"`
	UpdatedAt                    sql.NullTime   `json:"updated_at"`
}
