// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package sqlc

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Querier interface {
	AddCodeToUser(ctx context.Context, arg AddCodeToUserParams) error
	AssignRoleToUser(ctx context.Context, arg AssignRoleToUserParams) error
	AssignUserRole(ctx context.Context, arg AssignUserRoleParams) error
	CountReports(ctx context.Context, status sql.NullString) (int64, error)
	CountUserUnreadNotifications(ctx context.Context, userID uuid.UUID) (int64, error)
	CreateAlert(ctx context.Context, arg CreateAlertParams) error
	CreateAlertNotification(ctx context.Context, arg CreateAlertNotificationParams) error
	CreateEntity(ctx context.Context, arg CreateEntityParams) (Entity, error)
	CreateLocationSharing(ctx context.Context, arg CreateLocationSharingParams) error
	CreateReport(ctx context.Context, arg CreateReportParams) (uuid.UUID, error)
	CreateReportNotification(ctx context.Context, arg CreateReportNotificationParams) error
	CreateRiskTopic(ctx context.Context, arg CreateRiskTopicParams) (RiskTopic, error)
	CreateRiskType(ctx context.Context, arg CreateRiskTypeParams) error
	CreateRole(ctx context.Context, arg CreateRoleParams) (Role, error)
	CreateUser(ctx context.Context, arg CreateUserParams) error
	DeactivateExpiredLocationSharings(ctx context.Context, expiresAt time.Time) error
	DeleteEntity(ctx context.Context, id uuid.UUID) error
	DeleteLocationSharing(ctx context.Context, id uuid.UUID) error
	DeleteReport(ctx context.Context, id uuid.UUID) error
	DeleteRiskTopic(ctx context.Context, id uuid.UUID) error
	DeleteRiskType(ctx context.Context, id uuid.UUID) error
	ExpireAlert(ctx context.Context, id uuid.UUID) error
	GetEntitiesByType(ctx context.Context, entityType interface{}) ([]Entity, error)
	GetLocationSharingByID(ctx context.Context, id uuid.UUID) (LocationSharing, error)
	GetLocationSharingByToken(ctx context.Context, token string) (LocationSharing, error)
	GetReportByID(ctx context.Context, id uuid.UUID) (Report, error)
	GetRiskTopicByID(ctx context.Context, id uuid.UUID) (RiskTopic, error)
	GetRiskTypeByID(ctx context.Context, id uuid.UUID) (RiskType, error)
	GetRoleByName(ctx context.Context, name string) (Role, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetUserRoles(ctx context.Context, userID uuid.UUID) ([]Role, error)
	GetUsersByRole(ctx context.Context, roleID uuid.UUID) ([]GetUsersByRoleRow, error)
	ListActiveAlerts(ctx context.Context) ([]Alert, error)
	ListActiveLocationSharingsByDeviceID(ctx context.Context, deviceID sql.NullString) ([]LocationSharing, error)
	ListActiveLocationSharingsByUserID(ctx context.Context, userID uuid.NullUUID) ([]LocationSharing, error)
	ListAllDeviceTokensExceptUser(ctx context.Context, id uuid.UUID) ([]ListAllDeviceTokensExceptUserRow, error)
	ListAllLocationSharings(ctx context.Context) ([]LocationSharing, error)
	ListDeviceTokensByUserIDs(ctx context.Context, dollar_1 []uuid.UUID) ([]ListDeviceTokensByUserIDsRow, error)
	ListEntities(ctx context.Context) ([]Entity, error)
	ListNearbyUsers(ctx context.Context) ([]User, error)
	ListReportsByIDs(ctx context.Context, dollar_1 []uuid.UUID) ([]Report, error)
	ListReportsByStatus(ctx context.Context, status interface{}) ([]Report, error)
	ListReportsByUser(ctx context.Context, userID uuid.UUID) ([]Report, error)
	ListReportsWithPagination(ctx context.Context, arg ListReportsWithPaginationParams) ([]Report, error)
	ListRiskTopics(ctx context.Context) ([]RiskTopic, error)
	ListRiskTopicsByType(ctx context.Context, riskTypeID uuid.UUID) ([]RiskTopic, error)
	ListRiskTypes(ctx context.Context) ([]RiskType, error)
	ListRoles(ctx context.Context) ([]Role, error)
	ListUserNotifications(ctx context.Context, arg ListUserNotificationsParams) ([]Notification, error)
	MarkAlertSeen(ctx context.Context, arg MarkAlertSeenParams) error
	MarkEmailVerified(ctx context.Context, id uuid.UUID) error
	RejectReport(ctx context.Context, id uuid.UUID) error
	ResolveAlert(ctx context.Context, id uuid.UUID) error
	ResolveReport(ctx context.Context, id uuid.UUID) error
	UpdateAlertRadius(ctx context.Context, arg UpdateAlertRadiusParams) error
	UpdateEmailVerificationCode(ctx context.Context, arg UpdateEmailVerificationCodeParams) error
	UpdateLocationSharing(ctx context.Context, arg UpdateLocationSharingParams) error
	UpdateReport(ctx context.Context, arg UpdateReportParams) error
	UpdateReportLocation(ctx context.Context, arg UpdateReportLocationParams) (UpdateReportLocationRow, error)
	UpdateRiskType(ctx context.Context, arg UpdateRiskTypeParams) error
	UpdateUserDeviceInfo(ctx context.Context, arg UpdateUserDeviceInfoParams) error
	UpdateUserLocation(ctx context.Context, arg UpdateUserLocationParams) error
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	UpdateUserSavedLocations(ctx context.Context, arg UpdateUserSavedLocationsParams) error
	VerifyReport(ctx context.Context, arg VerifyReportParams) error
}

var _ Querier = (*Queries)(nil)
