// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AddCodeToUser(ctx context.Context, arg AddCodeToUserParams) error
	AssignRoleToUser(ctx context.Context, arg AssignRoleToUserParams) error
	AssignUserRole(ctx context.Context, arg AssignUserRoleParams) error
	CountUserUnreadNotifications(ctx context.Context, userID uuid.UUID) (int64, error)
	CreateAlert(ctx context.Context, arg CreateAlertParams) error
	CreateAlertNotification(ctx context.Context, arg CreateAlertNotificationParams) error
	CreateEntity(ctx context.Context, arg CreateEntityParams) (Entity, error)
	CreateReport(ctx context.Context, arg CreateReportParams) error
	CreateReportNotification(ctx context.Context, arg CreateReportNotificationParams) error
	CreateRiskTopic(ctx context.Context, arg CreateRiskTopicParams) (RiskTopic, error)
	CreateRiskType(ctx context.Context, arg CreateRiskTypeParams) error
	CreateRole(ctx context.Context, arg CreateRoleParams) (Role, error)
	CreateUser(ctx context.Context, arg CreateUserParams) error
	DeleteEntity(ctx context.Context, id uuid.UUID) error
	DeleteReport(ctx context.Context, id uuid.UUID) error
	DeleteRiskTopic(ctx context.Context, id uuid.UUID) error
	DeleteRiskType(ctx context.Context, id uuid.UUID) error
	ExpireAlert(ctx context.Context, id uuid.UUID) error
	GetEntitiesByType(ctx context.Context, entityType interface{}) ([]Entity, error)
	GetReportByID(ctx context.Context, id uuid.UUID) (Report, error)
	GetRiskTopicByID(ctx context.Context, id uuid.UUID) (RiskTopic, error)
	GetRiskTypeByID(ctx context.Context, id uuid.UUID) (RiskType, error)
	GetRoleByName(ctx context.Context, name string) (Role, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetUserRoles(ctx context.Context, userID uuid.UUID) ([]Role, error)
	GetUsersByRole(ctx context.Context, roleID uuid.UUID) ([]GetUsersByRoleRow, error)
	ListActiveAlerts(ctx context.Context) ([]Alert, error)
	ListAllDeviceTokensExceptUser(ctx context.Context, id uuid.UUID) ([]ListAllDeviceTokensExceptUserRow, error)
	ListDeviceTokensByUserIDs(ctx context.Context, dollar_1 []uuid.UUID) ([]ListDeviceTokensByUserIDsRow, error)
	ListEntities(ctx context.Context) ([]Entity, error)
	ListNearbyUsers(ctx context.Context) ([]User, error)
	ListReportsByStatus(ctx context.Context, status interface{}) ([]Report, error)
	ListReportsByUser(ctx context.Context, userID uuid.UUID) ([]Report, error)
	ListReportsNearby(ctx context.Context, arg ListReportsNearbyParams) ([]Report, error)
	ListRiskTopics(ctx context.Context) ([]RiskTopic, error)
	ListRiskTopicsByType(ctx context.Context, riskTypeID uuid.UUID) ([]RiskTopic, error)
	ListRiskTypes(ctx context.Context) ([]RiskType, error)
	ListRoles(ctx context.Context) ([]Role, error)
	ListUserNotifications(ctx context.Context, arg ListUserNotificationsParams) ([]Notification, error)
	MarkAlertSeen(ctx context.Context, arg MarkAlertSeenParams) error
	MarkEmailVerified(ctx context.Context, id uuid.UUID) error
	RejectReport(ctx context.Context, id uuid.UUID) error
	ResolveAlert(ctx context.Context, id uuid.UUID) error
	ResolveReport(ctx context.Context, id uuid.UUID) error
	UpdateAlertRadius(ctx context.Context, arg UpdateAlertRadiusParams) error
	UpdateEmailVerificationCode(ctx context.Context, arg UpdateEmailVerificationCodeParams) error
	UpdateReport(ctx context.Context, arg UpdateReportParams) error
	UpdateRiskType(ctx context.Context, arg UpdateRiskTypeParams) error
	UpdateUserDeviceInfo(ctx context.Context, arg UpdateUserDeviceInfoParams) error
	UpdateUserLocation(ctx context.Context, arg UpdateUserLocationParams) error
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	VerifyReport(ctx context.Context, arg VerifyReportParams) error
}

var _ Querier = (*Queries)(nil)
