// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package sqlc

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Querier interface {
	AddAnonymousReportVote(ctx context.Context, arg AddAnonymousReportVoteParams) error
	AddCodeToUser(ctx context.Context, arg AddCodeToUserParams) error
	AddUserReportVote(ctx context.Context, arg AddUserReportVoteParams) error
	AssignPermissionToRole(ctx context.Context, arg AssignPermissionToRoleParams) error
	AssignRoleToUser(ctx context.Context, arg AssignRoleToUserParams) error
	AssignUserRole(ctx context.Context, arg AssignUserRoleParams) error
	CountAlertSubscribers(ctx context.Context, alertID uuid.UUID) (int64, error)
	CountPriorityEmergencyContactsByUserID(ctx context.Context, userID uuid.UUID) (int64, error)
	CountReports(ctx context.Context, status sql.NullString) (int64, error)
	CountUserUnreadNotifications(ctx context.Context, userID uuid.UUID) (int64, error)
	CreateAlert(ctx context.Context, arg CreateAlertParams) error
	CreateAlertNotification(ctx context.Context, arg CreateAlertNotificationParams) error
	// Anonymous User Queries
	CreateAnonymousAlert(ctx context.Context, arg CreateAnonymousAlertParams) error
	// Cria um novo log de migração
	CreateAnonymousMigration(ctx context.Context, arg CreateAnonymousMigrationParams) error
	// Cria um novo mapeamento device ↔ user
	CreateDeviceUserMapping(ctx context.Context, arg CreateDeviceUserMappingParams) error
	CreateEmergencyContact(ctx context.Context, arg CreateEmergencyContactParams) error
	CreateEntity(ctx context.Context, arg CreateEntityParams) (Entity, error)
	CreateLocationSharing(ctx context.Context, arg CreateLocationSharingParams) error
	CreatePermission(ctx context.Context, arg CreatePermissionParams) (Permission, error)
	CreateReport(ctx context.Context, arg CreateReportParams) (uuid.UUID, error)
	CreateReportNotification(ctx context.Context, arg CreateReportNotificationParams) error
	CreateRiskTopic(ctx context.Context, arg CreateRiskTopicParams) (RiskTopic, error)
	CreateRiskType(ctx context.Context, arg CreateRiskTypeParams) error
	CreateRole(ctx context.Context, arg CreateRoleParams) (Role, error)
	CreateUser(ctx context.Context, arg CreateUserParams) error
	// Marca um mapeamento como inativo
	DeactivateDeviceUserMapping(ctx context.Context, id uuid.UUID) error
	DeactivateExpiredLocationSharings(ctx context.Context, expiresAt time.Time) error
	DeleteAlert(ctx context.Context, arg DeleteAlertParams) error
	// Apenas se anon mais recente
	// Remove configurações anônimas após merge
	DeleteAnonymousSafetySettings(ctx context.Context, anonymousSessionID uuid.UUID) error
	DeleteEmergencyContact(ctx context.Context, id uuid.UUID) error
	DeleteEmergencyContactByUserIDAndID(ctx context.Context, arg DeleteEmergencyContactByUserIDAndIDParams) error
	DeleteEntity(ctx context.Context, id uuid.UUID) error
	DeleteLocationSharing(ctx context.Context, id uuid.UUID) error
	DeleteReport(ctx context.Context, id uuid.UUID) error
	DeleteRiskTopic(ctx context.Context, id uuid.UUID) error
	DeleteRiskType(ctx context.Context, id uuid.UUID) error
	DeleteSafetySettingsByAnonymousSessionID(ctx context.Context, arg DeleteSafetySettingsByAnonymousSessionIDParams) error
	ExpireAlert(ctx context.Context, id uuid.UUID) error
	ExpireOldReports(ctx context.Context, expiresAt sql.NullTime) error
	FindDuplicateReports(ctx context.Context, arg FindDuplicateReportsParams) ([]FindDuplicateReportsRow, error)
	// Retorna o mapeamento ativo de um device
	GetActiveDeviceUserMapping(ctx context.Context, deviceID string) (DeviceUserMapping, error)
	GetAlertByID(ctx context.Context, id uuid.UUID) (GetAlertByIDRow, error)
	GetAlertsByAnonymousSessionID(ctx context.Context, arg GetAlertsByAnonymousSessionIDParams) ([]GetAlertsByAnonymousSessionIDRow, error)
	GetAlertsByUserID(ctx context.Context, createdBy uuid.NullUUID) ([]GetAlertsByUserIDRow, error)
	// Retorna contadores de dados anônimos antes da migração
	GetAnonymousDataCounts(ctx context.Context, anonymousSessionID uuid.UUID) (GetAnonymousDataCountsRow, error)
	GetAnonymousVote(ctx context.Context, arg GetAnonymousVoteParams) (ReportVote, error)
	// Retorna todos os devices vinculados a um usuário
	GetDeviceUserMappingsByUserID(ctx context.Context, userID uuid.UUID) ([]DeviceUserMapping, error)
	GetEmergencyContactByID(ctx context.Context, id uuid.UUID) (EmergencyContact, error)
	GetEmergencyContactByUserIDAndID(ctx context.Context, arg GetEmergencyContactByUserIDAndIDParams) (EmergencyContact, error)
	GetEmergencyContactsByUserID(ctx context.Context, userID uuid.UUID) ([]EmergencyContact, error)
	GetEntitiesByType(ctx context.Context, entityType interface{}) ([]Entity, error)
	GetLocationSharingByID(ctx context.Context, id uuid.UUID) (LocationSharing, error)
	GetLocationSharingByToken(ctx context.Context, token string) (LocationSharing, error)
	// Retorna uma migração específica
	GetMigrationByID(ctx context.Context, id uuid.UUID) (AnonymousUserMigration, error)
	// ============================================================================
	// ANALYTICS QUERIES
	// ============================================================================
	// Retorna estatísticas gerais de migrações
	GetMigrationStats(ctx context.Context, since time.Time) (GetMigrationStatsRow, error)
	// Retorna todas as migrações de um device
	GetMigrationsByDeviceID(ctx context.Context, deviceID string) ([]AnonymousUserMigration, error)
	// Retorna todas as migrações de um usuário
	GetMigrationsByUserID(ctx context.Context, userID uuid.UUID) ([]AnonymousUserMigration, error)
	GetPermissionByCode(ctx context.Context, code sql.NullString) (Permission, error)
	GetPriorityEmergencyContactsByUserID(ctx context.Context, userID uuid.UUID) ([]EmergencyContact, error)
	// Retorna migrações falhadas recentes para debug
	GetRecentFailedMigrations(ctx context.Context, limit int32) ([]AnonymousUserMigration, error)
	GetReportByID(ctx context.Context, id uuid.UUID) (GetReportByIDRow, error)
	GetRiskTopicByID(ctx context.Context, id uuid.UUID) (RiskTopic, error)
	GetRiskTypeByID(ctx context.Context, id uuid.UUID) (RiskType, error)
	GetRoleByName(ctx context.Context, name string) (Role, error)
	GetRolePermissions(ctx context.Context, roleID uuid.UUID) ([]Permission, error)
	// ============================================================================
	// QUERIES FOR MERGE STRATEGY (Settings Conflict Resolution)
	// ============================================================================
	// Retorna configurações de uma sessão anônima
	GetSafetySettingsByAnonymousSession(ctx context.Context, anonymousSessionID uuid.UUID) (UserSafetySetting, error)
	// Anonymous User Queries
	GetSafetySettingsByAnonymousSessionID(ctx context.Context, deviceID sql.NullString) (UserSafetySetting, error)
	GetSafetySettingsByUserID(ctx context.Context, userID uuid.NullUUID) (UserSafetySetting, error)
	GetSubscribedAlerts(ctx context.Context, userID uuid.NullUUID) ([]GetSubscribedAlertsRow, error)
	GetSubscribedAlertsAnonymous(ctx context.Context, arg GetSubscribedAlertsAnonymousParams) ([]Alert, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByEmailOrPhone(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	// Retorna histórico completo de migrações de um usuário
	GetUserMigrationHistory(ctx context.Context, userID uuid.UUID) ([]GetUserMigrationHistoryRow, error)
	GetUserPermissions(ctx context.Context, userID uuid.UUID) ([]Permission, error)
	GetUserRoles(ctx context.Context, userID uuid.UUID) ([]Role, error)
	// Retorna configurações de um usuário autenticado
	GetUserSafetySettings(ctx context.Context, userID uuid.UUID) (UserSafetySetting, error)
	GetUserVote(ctx context.Context, arg GetUserVoteParams) (ReportVote, error)
	GetUsersByRole(ctx context.Context, roleID uuid.UUID) ([]GetUsersByRoleRow, error)
	HasPermission(ctx context.Context, arg HasPermissionParams) (bool, error)
	IncrementUserReportsSubmitted(ctx context.Context, id uuid.UUID) error
	IncrementUserReportsVerified(ctx context.Context, id uuid.UUID) error
	IsAnonymousSubscribed(ctx context.Context, arg IsAnonymousSubscribedParams) (bool, error)
	IsAnonymousSubscribedToAlert(ctx context.Context, arg IsAnonymousSubscribedToAlertParams) (bool, error)
	IsUserSubscribed(ctx context.Context, arg IsUserSubscribedParams) (bool, error)
	IsUserSubscribedToAlert(ctx context.Context, arg IsUserSubscribedToAlertParams) (bool, error)
	ListActiveAlerts(ctx context.Context) ([]ListActiveAlertsRow, error)
	ListActiveLocationSharingsByDeviceID(ctx context.Context, deviceID sql.NullString) ([]LocationSharing, error)
	ListActiveLocationSharingsByUserID(ctx context.Context, userID uuid.NullUUID) ([]LocationSharing, error)
	ListAllDeviceTokensExceptUser(ctx context.Context, id uuid.UUID) ([]ListAllDeviceTokensExceptUserRow, error)
	ListAllLocationSharings(ctx context.Context) ([]LocationSharing, error)
	ListAnonymousTokensForAlertNotification(ctx context.Context, arg ListAnonymousTokensForAlertNotificationParams) ([]ListAnonymousTokensForAlertNotificationRow, error)
	ListAnonymousTokensForReportNotification(ctx context.Context, arg ListAnonymousTokensForReportNotificationParams) ([]ListAnonymousTokensForReportNotificationRow, error)
	ListDeviceTokensByUserIDs(ctx context.Context, dollar_1 []uuid.UUID) ([]ListDeviceTokensByUserIDsRow, error)
	ListDeviceTokensForAlertNotification(ctx context.Context, arg ListDeviceTokensForAlertNotificationParams) ([]ListDeviceTokensForAlertNotificationRow, error)
	ListDeviceTokensForReportNotification(ctx context.Context, arg ListDeviceTokensForReportNotificationParams) ([]ListDeviceTokensForReportNotificationRow, error)
	ListEntities(ctx context.Context) ([]Entity, error)
	ListNearbyUsers(ctx context.Context) ([]User, error)
	ListPermissions(ctx context.Context) ([]Permission, error)
	ListReportsByIDs(ctx context.Context, dollar_1 []uuid.UUID) ([]ListReportsByIDsRow, error)
	ListReportsByStatus(ctx context.Context, status interface{}) ([]ListReportsByStatusRow, error)
	ListReportsByUser(ctx context.Context, userID uuid.UUID) ([]ListReportsByUserRow, error)
	ListReportsWithPagination(ctx context.Context, arg ListReportsWithPaginationParams) ([]ListReportsWithPaginationRow, error)
	ListRiskTopics(ctx context.Context) ([]RiskTopic, error)
	ListRiskTopicsByType(ctx context.Context, riskTypeID uuid.UUID) ([]RiskTopic, error)
	ListRiskTypes(ctx context.Context) ([]RiskType, error)
	ListRoles(ctx context.Context) ([]Role, error)
	ListUserNotifications(ctx context.Context, arg ListUserNotificationsParams) ([]Notification, error)
	MarkAccountVerified(ctx context.Context, id uuid.UUID) error
	MarkAlertSeen(ctx context.Context, arg MarkAlertSeenParams) error
	// Marca uma sessão anônima como migrada
	MarkAnonymousSessionAsMigrated(ctx context.Context, arg MarkAnonymousSessionAsMigratedParams) error
	// Marca uma migração como concluída
	MarkMigrationCompleted(ctx context.Context, id uuid.UUID) error
	// Marca uma migração como falha
	MarkMigrationFailed(ctx context.Context, arg MarkMigrationFailedParams) error
	// Merge inteligente: prioriza configurações anônimas se mais recentes
	MergeSafetySettings(ctx context.Context, arg MergeSafetySettingsParams) error
	// ============================================================================
	// SQLC QUERIES FOR ANONYMOUS TO AUTHENTICATED USER MIGRATION
	// ============================================================================
	// File: internal/adapter/repository/postgres/queries/anonymous_migration.sql
	// Purpose: Type-safe queries for migrating anonymous user data
	// ============================================================================
	// Migra todos os alertas de uma sessão anônima para um usuário autenticado
	MigrateAlertsToUser(ctx context.Context, arg MigrateAlertsToUserParams) (int64, error)
	// Migra compartilhamentos de localização de uma sessão anônima para um usuário autenticado
	MigrateLocationSharingsToUser(ctx context.Context, arg MigrateLocationSharingsToUserParams) (int64, error)
	// Migra configurações de segurança de uma sessão anônima para um usuário autenticado
	// NOTA: Apenas migra se o usuário NÃO tiver configurações
	MigrateSafetySettingsToUser(ctx context.Context, arg MigrateSafetySettingsToUserParams) (int64, error)
	// Migra todas as subscrições de uma sessão anônima para um usuário autenticado
	MigrateSubscriptionsToUser(ctx context.Context, arg MigrateSubscriptionsToUserParams) (int64, error)
	RejectReport(ctx context.Context, id uuid.UUID) error
	RemoveAnonymousVote(ctx context.Context, arg RemoveAnonymousVoteParams) error
	RemovePermissionFromRole(ctx context.Context, arg RemovePermissionFromRoleParams) error
	RemoveUserVote(ctx context.Context, arg RemoveUserVoteParams) error
	ResolveAlert(ctx context.Context, id uuid.UUID) error
	ResolveReport(ctx context.Context, id uuid.UUID) error
	// ============================================================================
	// QUERIES FOR ROLLBACK (Error Recovery)
	// ============================================================================
	// Reverte migração de alertas (rollback)
	RollbackAlertsToAnonymous(ctx context.Context, arg RollbackAlertsToAnonymousParams) (int64, error)
	// Reverte status de migração da sessão anônima
	RollbackAnonymousSessionMigration(ctx context.Context, anonymousSessionID uuid.UUID) error
	// Reverte migração de subscrições (rollback)
	RollbackSubscriptionsToAnonymous(ctx context.Context, arg RollbackSubscriptionsToAnonymousParams) (int64, error)
	SubscribeAnonymousToAlert(ctx context.Context, arg SubscribeAnonymousToAlertParams) error
	SubscribeToAlert(ctx context.Context, arg SubscribeToAlertParams) error
	UnsubscribeAnonymousFromAlert(ctx context.Context, arg UnsubscribeAnonymousFromAlertParams) error
	UnsubscribeFromAlert(ctx context.Context, arg UnsubscribeFromAlertParams) error
	UpdateAlert(ctx context.Context, arg UpdateAlertParams) error
	UpdateAlertAnonymousToUser(ctx context.Context, arg UpdateAlertAnonymousToUserParams) error
	UpdateAlertRadius(ctx context.Context, arg UpdateAlertRadiusParams) error
	UpdateAlertSubscriptionsAnonymousToUser(ctx context.Context, arg UpdateAlertSubscriptionsAnonymousToUserParams) error
	UpdateEmailVerificationCode(ctx context.Context, arg UpdateEmailVerificationCodeParams) error
	UpdateEmergencyContact(ctx context.Context, arg UpdateEmergencyContactParams) error
	UpdateLocationSharing(ctx context.Context, arg UpdateLocationSharingParams) error
	// Atualiza os contadores de uma migração
	UpdateMigrationCounters(ctx context.Context, arg UpdateMigrationCountersParams) error
	UpdateReport(ctx context.Context, arg UpdateReportParams) error
	UpdateReportLocation(ctx context.Context, arg UpdateReportLocationParams) (UpdateReportLocationRow, error)
	UpdateRiskTopicIcon(ctx context.Context, arg UpdateRiskTopicIconParams) error
	UpdateRiskType(ctx context.Context, arg UpdateRiskTypeParams) error
	UpdateRiskTypeIcon(ctx context.Context, arg UpdateRiskTypeIconParams) error
	UpdateRiskTypeIsEnabled(ctx context.Context, arg UpdateRiskTypeIsEnabledParams) error
	UpdateUserDeviceInfo(ctx context.Context, arg UpdateUserDeviceInfoParams) error
	UpdateUserLocation(ctx context.Context, arg UpdateUserLocationParams) error
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	UpdateUserSavedLocations(ctx context.Context, arg UpdateUserSavedLocationsParams) error
	UpdateUserTrustScore(ctx context.Context, arg UpdateUserTrustScoreParams) error
	UpdateVerificationCounts(ctx context.Context, arg UpdateVerificationCountsParams) error
	UpsertAnonymousSafetySettings(ctx context.Context, arg UpsertAnonymousSafetySettingsParams) error
	UpsertSafetySettings(ctx context.Context, arg UpsertSafetySettingsParams) error
	VerifyReport(ctx context.Context, arg VerifyReportParams) error
}

var _ Querier = (*Queries)(nil)
