// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: reports.sql

package sqlc

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const countReports = `-- name: CountReports :one
SELECT COUNT(*) FROM reports
WHERE ($1::text IS NULL OR status = $1::report_status)
`

func (q *Queries) CountReports(ctx context.Context, status sql.NullString) (int64, error) {
	row := q.db.QueryRowContext(ctx, countReports, status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createReport = `-- name: CreateReport :one
INSERT INTO reports (
    user_id, risk_type_id, risk_topic_id, description,
    latitude, longitude, province, municipality,
    neighborhood, address, image_url
) VALUES (
             $1, $2, $3, $4, $5,
             $6, $7, $8, $9, $10, $11
         )
RETURNING id
`

type CreateReportParams struct {
	UserID       uuid.UUID      `json:"user_id"`
	RiskTypeID   uuid.UUID      `json:"risk_type_id"`
	RiskTopicID  uuid.NullUUID  `json:"risk_topic_id"`
	Description  sql.NullString `json:"description"`
	Latitude     float64        `json:"latitude"`
	Longitude    float64        `json:"longitude"`
	Province     sql.NullString `json:"province"`
	Municipality sql.NullString `json:"municipality"`
	Neighborhood sql.NullString `json:"neighborhood"`
	Address      sql.NullString `json:"address"`
	ImageUrl     sql.NullString `json:"image_url"`
}

func (q *Queries) CreateReport(ctx context.Context, arg CreateReportParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, createReport,
		arg.UserID,
		arg.RiskTypeID,
		arg.RiskTopicID,
		arg.Description,
		arg.Latitude,
		arg.Longitude,
		arg.Province,
		arg.Municipality,
		arg.Neighborhood,
		arg.Address,
		arg.ImageUrl,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const createReportNotification = `-- name: CreateReportNotification :exec
INSERT INTO notifications (type, reference_id, user_id) VALUES ($1, $2, $3)
ON CONFLICT (type, reference_id, user_id) DO NOTHING
`

type CreateReportNotificationParams struct {
	Type        NotificationType `json:"type"`
	ReferenceID uuid.UUID        `json:"reference_id"`
	UserID      uuid.UUID        `json:"user_id"`
}

func (q *Queries) CreateReportNotification(ctx context.Context, arg CreateReportNotificationParams) error {
	_, err := q.db.ExecContext(ctx, createReportNotification, arg.Type, arg.ReferenceID, arg.UserID)
	return err
}

const deleteReport = `-- name: DeleteReport :exec
DELETE FROM reports WHERE id = $1
`

func (q *Queries) DeleteReport(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteReport, id)
	return err
}

const getReportByID = `-- name: GetReportByID :one
SELECT id, user_id, risk_type_id, risk_topic_id, description, latitude, longitude, province, municipality, neighborhood, address, image_url, status, reviewed_by, resolved_at, created_at, updated_at FROM reports WHERE id = $1
`

func (q *Queries) GetReportByID(ctx context.Context, id uuid.UUID) (Report, error) {
	row := q.db.QueryRowContext(ctx, getReportByID, id)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RiskTypeID,
		&i.RiskTopicID,
		&i.Description,
		&i.Latitude,
		&i.Longitude,
		&i.Province,
		&i.Municipality,
		&i.Neighborhood,
		&i.Address,
		&i.ImageUrl,
		&i.Status,
		&i.ReviewedBy,
		&i.ResolvedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listReportsByIDs = `-- name: ListReportsByIDs :many
SELECT
    id, user_id, risk_type_id, risk_topic_id, description,
    latitude, longitude, province, municipality, neighborhood,
    address, image_url, status, reviewed_by, resolved_at,
    created_at, updated_at
FROM reports
WHERE id = ANY($1::uuid[])
ORDER BY created_at DESC
`

func (q *Queries) ListReportsByIDs(ctx context.Context, dollar_1 []uuid.UUID) ([]Report, error) {
	rows, err := q.db.QueryContext(ctx, listReportsByIDs, pq.Array(dollar_1))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Report{}
	for rows.Next() {
		var i Report
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.RiskTypeID,
			&i.RiskTopicID,
			&i.Description,
			&i.Latitude,
			&i.Longitude,
			&i.Province,
			&i.Municipality,
			&i.Neighborhood,
			&i.Address,
			&i.ImageUrl,
			&i.Status,
			&i.ReviewedBy,
			&i.ResolvedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReportsByStatus = `-- name: ListReportsByStatus :many
SELECT id, user_id, risk_type_id, risk_topic_id, description, latitude, longitude, province, municipality, neighborhood, address, image_url, status, reviewed_by, resolved_at, created_at, updated_at FROM reports WHERE status = $1 ORDER BY created_at DESC
`

func (q *Queries) ListReportsByStatus(ctx context.Context, status interface{}) ([]Report, error) {
	rows, err := q.db.QueryContext(ctx, listReportsByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Report{}
	for rows.Next() {
		var i Report
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.RiskTypeID,
			&i.RiskTopicID,
			&i.Description,
			&i.Latitude,
			&i.Longitude,
			&i.Province,
			&i.Municipality,
			&i.Neighborhood,
			&i.Address,
			&i.ImageUrl,
			&i.Status,
			&i.ReviewedBy,
			&i.ResolvedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReportsByUser = `-- name: ListReportsByUser :many
SELECT id, user_id, risk_type_id, risk_topic_id, description, latitude, longitude, province, municipality, neighborhood, address, image_url, status, reviewed_by, resolved_at, created_at, updated_at FROM reports WHERE user_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListReportsByUser(ctx context.Context, userID uuid.UUID) ([]Report, error) {
	rows, err := q.db.QueryContext(ctx, listReportsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Report{}
	for rows.Next() {
		var i Report
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.RiskTypeID,
			&i.RiskTopicID,
			&i.Description,
			&i.Latitude,
			&i.Longitude,
			&i.Province,
			&i.Municipality,
			&i.Neighborhood,
			&i.Address,
			&i.ImageUrl,
			&i.Status,
			&i.ReviewedBy,
			&i.ResolvedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReportsWithPagination = `-- name: ListReportsWithPagination :many
SELECT
    id, user_id, risk_type_id, risk_topic_id, description,
    latitude, longitude, province, municipality, neighborhood,
    address, image_url, status, reviewed_by, resolved_at,
    created_at, updated_at
FROM reports
WHERE ($4::text IS NULL OR status = $4::report_status)
ORDER BY
    CASE WHEN $1 = 'desc' THEN created_at END DESC,
    CASE WHEN $1 = 'asc' THEN created_at END ASC
LIMIT $2 OFFSET $3
`

type ListReportsWithPaginationParams struct {
	Column1 interface{}    `json:"column_1"`
	Limit   int32          `json:"limit"`
	Offset  int32          `json:"offset"`
	Status  sql.NullString `json:"status"`
}

func (q *Queries) ListReportsWithPagination(ctx context.Context, arg ListReportsWithPaginationParams) ([]Report, error) {
	rows, err := q.db.QueryContext(ctx, listReportsWithPagination,
		arg.Column1,
		arg.Limit,
		arg.Offset,
		arg.Status,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Report{}
	for rows.Next() {
		var i Report
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.RiskTypeID,
			&i.RiskTopicID,
			&i.Description,
			&i.Latitude,
			&i.Longitude,
			&i.Province,
			&i.Municipality,
			&i.Neighborhood,
			&i.Address,
			&i.ImageUrl,
			&i.Status,
			&i.ReviewedBy,
			&i.ResolvedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rejectReport = `-- name: RejectReport :exec
UPDATE reports
SET status = 'rejected',
    updated_at = NOW()
WHERE id = $1
`

func (q *Queries) RejectReport(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, rejectReport, id)
	return err
}

const resolveReport = `-- name: ResolveReport :exec
UPDATE reports
SET status = 'resolved',
    resolved_at = NOW(),
    updated_at = NOW()
WHERE id = $1
`

func (q *Queries) ResolveReport(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, resolveReport, id)
	return err
}

const updateReport = `-- name: UpdateReport :exec
UPDATE reports
SET description = $2,
    status = $3,
    updated_at = NOW()
WHERE id = $1
`

type UpdateReportParams struct {
	ID          uuid.UUID      `json:"id"`
	Description sql.NullString `json:"description"`
	Status      interface{}    `json:"status"`
}

func (q *Queries) UpdateReport(ctx context.Context, arg UpdateReportParams) error {
	_, err := q.db.ExecContext(ctx, updateReport, arg.ID, arg.Description, arg.Status)
	return err
}

const updateReportLocation = `-- name: UpdateReportLocation :one
UPDATE reports
SET latitude = $2,
    longitude = $3,
    address = COALESCE(NULLIF($4, ''), address),
    neighborhood = COALESCE(NULLIF($5, ''), neighborhood),
    municipality = COALESCE(NULLIF($6, ''), municipality),
    province = COALESCE(NULLIF($7, ''), province),
    updated_at = NOW()
WHERE id = $1
RETURNING id, updated_at
`

type UpdateReportLocationParams struct {
	ID        uuid.UUID   `json:"id"`
	Latitude  float64     `json:"latitude"`
	Longitude float64     `json:"longitude"`
	Column4   interface{} `json:"column_4"`
	Column5   interface{} `json:"column_5"`
	Column6   interface{} `json:"column_6"`
	Column7   interface{} `json:"column_7"`
}

type UpdateReportLocationRow struct {
	ID        uuid.UUID    `json:"id"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}

func (q *Queries) UpdateReportLocation(ctx context.Context, arg UpdateReportLocationParams) (UpdateReportLocationRow, error) {
	row := q.db.QueryRowContext(ctx, updateReportLocation,
		arg.ID,
		arg.Latitude,
		arg.Longitude,
		arg.Column4,
		arg.Column5,
		arg.Column6,
		arg.Column7,
	)
	var i UpdateReportLocationRow
	err := row.Scan(&i.ID, &i.UpdatedAt)
	return i, err
}

const verifyReport = `-- name: VerifyReport :exec
UPDATE reports
SET status = 'verified', reviewed_by = $2, updated_at = NOW()
WHERE id = $1
`

type VerifyReportParams struct {
	ID         uuid.UUID     `json:"id"`
	ReviewedBy uuid.NullUUID `json:"reviewed_by"`
}

func (q *Queries) VerifyReport(ctx context.Context, arg VerifyReportParams) error {
	_, err := q.db.ExecContext(ctx, verifyReport, arg.ID, arg.ReviewedBy)
	return err
}
