// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: risk_topics.sql

package sqlc

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createRiskTopic = `-- name: CreateRiskTopic :one
INSERT INTO risk_topics (risk_type_id, name, description)
VALUES ($1, $2, $3)
RETURNING id, risk_type_id, name, description, icon_path, is_sensitive, created_at, updated_at
`

type CreateRiskTopicParams struct {
	RiskTypeID  uuid.UUID      `json:"risk_type_id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
}

func (q *Queries) CreateRiskTopic(ctx context.Context, arg CreateRiskTopicParams) (RiskTopic, error) {
	row := q.db.QueryRowContext(ctx, createRiskTopic, arg.RiskTypeID, arg.Name, arg.Description)
	var i RiskTopic
	err := row.Scan(
		&i.ID,
		&i.RiskTypeID,
		&i.Name,
		&i.Description,
		&i.IconPath,
		&i.IsSensitive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteRiskTopic = `-- name: DeleteRiskTopic :exec
DELETE FROM risk_topics WHERE id = $1
`

func (q *Queries) DeleteRiskTopic(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteRiskTopic, id)
	return err
}

const getRiskTopicByID = `-- name: GetRiskTopicByID :one
SELECT id, risk_type_id, name, description, icon_path, is_sensitive, created_at, updated_at FROM risk_topics WHERE id = $1
`

func (q *Queries) GetRiskTopicByID(ctx context.Context, id uuid.UUID) (RiskTopic, error) {
	row := q.db.QueryRowContext(ctx, getRiskTopicByID, id)
	var i RiskTopic
	err := row.Scan(
		&i.ID,
		&i.RiskTypeID,
		&i.Name,
		&i.Description,
		&i.IconPath,
		&i.IsSensitive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRiskTopics = `-- name: ListRiskTopics :many
SELECT id, risk_type_id, name, description, icon_path, is_sensitive, created_at, updated_at FROM risk_topics ORDER BY created_at DESC
`

func (q *Queries) ListRiskTopics(ctx context.Context) ([]RiskTopic, error) {
	rows, err := q.db.QueryContext(ctx, listRiskTopics)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RiskTopic{}
	for rows.Next() {
		var i RiskTopic
		if err := rows.Scan(
			&i.ID,
			&i.RiskTypeID,
			&i.Name,
			&i.Description,
			&i.IconPath,
			&i.IsSensitive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRiskTopicsByType = `-- name: ListRiskTopicsByType :many
SELECT id, risk_type_id, name, description, icon_path, is_sensitive, created_at, updated_at FROM risk_topics WHERE risk_type_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListRiskTopicsByType(ctx context.Context, riskTypeID uuid.UUID) ([]RiskTopic, error) {
	rows, err := q.db.QueryContext(ctx, listRiskTopicsByType, riskTypeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RiskTopic{}
	for rows.Next() {
		var i RiskTopic
		if err := rows.Scan(
			&i.ID,
			&i.RiskTypeID,
			&i.Name,
			&i.Description,
			&i.IconPath,
			&i.IsSensitive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRiskTopicIcon = `-- name: UpdateRiskTopicIcon :exec
UPDATE risk_topics
SET icon_path = $2, updated_at = NOW()
WHERE id = $1
`

type UpdateRiskTopicIconParams struct {
	ID       uuid.UUID      `json:"id"`
	IconPath sql.NullString `json:"icon_path"`
}

func (q *Queries) UpdateRiskTopicIcon(ctx context.Context, arg UpdateRiskTopicIconParams) error {
	_, err := q.db.ExecContext(ctx, updateRiskTopicIcon, arg.ID, arg.IconPath)
	return err
}
