// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: risk_types.sql

package sqlc

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createRiskType = `-- name: CreateRiskType :exec
INSERT INTO risk_types (name, description, default_radius_meters)
VALUES ($1, $2, $3)
`

type CreateRiskTypeParams struct {
	Name                string         `json:"name"`
	Description         sql.NullString `json:"description"`
	DefaultRadiusMeters sql.NullInt32  `json:"default_radius_meters"`
}

func (q *Queries) CreateRiskType(ctx context.Context, arg CreateRiskTypeParams) error {
	_, err := q.db.ExecContext(ctx, createRiskType, arg.Name, arg.Description, arg.DefaultRadiusMeters)
	return err
}

const deleteRiskType = `-- name: DeleteRiskType :exec
DELETE FROM risk_types WHERE id = $1
`

func (q *Queries) DeleteRiskType(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteRiskType, id)
	return err
}

const getRiskTypeByID = `-- name: GetRiskTypeByID :one
SELECT id, name, description, default_radius_meters, created_at, updated_at FROM risk_types WHERE id = $1
`

func (q *Queries) GetRiskTypeByID(ctx context.Context, id uuid.UUID) (RiskType, error) {
	row := q.db.QueryRowContext(ctx, getRiskTypeByID, id)
	var i RiskType
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.DefaultRadiusMeters,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRiskTypes = `-- name: ListRiskTypes :many
SELECT id, name, description, default_radius_meters, created_at, updated_at FROM risk_types ORDER BY created_at DESC
`

func (q *Queries) ListRiskTypes(ctx context.Context) ([]RiskType, error) {
	rows, err := q.db.QueryContext(ctx, listRiskTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RiskType{}
	for rows.Next() {
		var i RiskType
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.DefaultRadiusMeters,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRiskType = `-- name: UpdateRiskType :exec
UPDATE risk_types
SET name = $2, description = $3, default_radius_meters = $4, updated_at = NOW()
WHERE id = $1
`

type UpdateRiskTypeParams struct {
	ID                  uuid.UUID      `json:"id"`
	Name                string         `json:"name"`
	Description         sql.NullString `json:"description"`
	DefaultRadiusMeters sql.NullInt32  `json:"default_radius_meters"`
}

func (q *Queries) UpdateRiskType(ctx context.Context, arg UpdateRiskTypeParams) error {
	_, err := q.db.ExecContext(ctx, updateRiskType,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.DefaultRadiusMeters,
	)
	return err
}
