// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: safety_settings.sql

package sqlc

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const deleteSafetySettingsByAnonymousSessionID = `-- name: DeleteSafetySettingsByAnonymousSessionID :exec
DELETE FROM user_safety_settings 
WHERE anonymous_session_id = $1 AND device_id = $2
`

type DeleteSafetySettingsByAnonymousSessionIDParams struct {
	AnonymousSessionID uuid.NullUUID  `json:"anonymous_session_id"`
	DeviceID           sql.NullString `json:"device_id"`
}

func (q *Queries) DeleteSafetySettingsByAnonymousSessionID(ctx context.Context, arg DeleteSafetySettingsByAnonymousSessionIDParams) error {
	_, err := q.db.ExecContext(ctx, deleteSafetySettingsByAnonymousSessionID, arg.AnonymousSessionID, arg.DeviceID)
	return err
}

const getSafetySettingsByAnonymousSessionID = `-- name: GetSafetySettingsByAnonymousSessionID :one

SELECT id, user_id, anonymous_session_id, device_id, notifications_enabled, notification_alert_types, notification_alert_radius_mins, notification_report_types, notification_report_radius_mins, location_sharing_enabled, location_history_enabled, profile_visibility, anonymous_reports, show_online_status, auto_alerts_enabled, danger_zones_enabled, time_based_alerts_enabled, high_risk_start_time, high_risk_end_time, night_mode_enabled, night_mode_start_time, night_mode_end_time, created_at, updated_at FROM user_safety_settings 
WHERE anonymous_session_id = $1 AND device_id = $2 
LIMIT 1
`

type GetSafetySettingsByAnonymousSessionIDParams struct {
	AnonymousSessionID uuid.NullUUID  `json:"anonymous_session_id"`
	DeviceID           sql.NullString `json:"device_id"`
}

// Anonymous User Queries
func (q *Queries) GetSafetySettingsByAnonymousSessionID(ctx context.Context, arg GetSafetySettingsByAnonymousSessionIDParams) (UserSafetySetting, error) {
	row := q.db.QueryRowContext(ctx, getSafetySettingsByAnonymousSessionID, arg.AnonymousSessionID, arg.DeviceID)
	var i UserSafetySetting
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AnonymousSessionID,
		&i.DeviceID,
		&i.NotificationsEnabled,
		pq.Array(&i.NotificationAlertTypes),
		&i.NotificationAlertRadiusMins,
		pq.Array(&i.NotificationReportTypes),
		&i.NotificationReportRadiusMins,
		&i.LocationSharingEnabled,
		&i.LocationHistoryEnabled,
		&i.ProfileVisibility,
		&i.AnonymousReports,
		&i.ShowOnlineStatus,
		&i.AutoAlertsEnabled,
		&i.DangerZonesEnabled,
		&i.TimeBasedAlertsEnabled,
		&i.HighRiskStartTime,
		&i.HighRiskEndTime,
		&i.NightModeEnabled,
		&i.NightModeStartTime,
		&i.NightModeEndTime,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSafetySettingsByUserID = `-- name: GetSafetySettingsByUserID :one
SELECT id, user_id, anonymous_session_id, device_id, notifications_enabled, notification_alert_types, notification_alert_radius_mins, notification_report_types, notification_report_radius_mins, location_sharing_enabled, location_history_enabled, profile_visibility, anonymous_reports, show_online_status, auto_alerts_enabled, danger_zones_enabled, time_based_alerts_enabled, high_risk_start_time, high_risk_end_time, night_mode_enabled, night_mode_start_time, night_mode_end_time, created_at, updated_at FROM user_safety_settings WHERE user_id = $1 LIMIT 1
`

func (q *Queries) GetSafetySettingsByUserID(ctx context.Context, userID uuid.NullUUID) (UserSafetySetting, error) {
	row := q.db.QueryRowContext(ctx, getSafetySettingsByUserID, userID)
	var i UserSafetySetting
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AnonymousSessionID,
		&i.DeviceID,
		&i.NotificationsEnabled,
		pq.Array(&i.NotificationAlertTypes),
		&i.NotificationAlertRadiusMins,
		pq.Array(&i.NotificationReportTypes),
		&i.NotificationReportRadiusMins,
		&i.LocationSharingEnabled,
		&i.LocationHistoryEnabled,
		&i.ProfileVisibility,
		&i.AnonymousReports,
		&i.ShowOnlineStatus,
		&i.AutoAlertsEnabled,
		&i.DangerZonesEnabled,
		&i.TimeBasedAlertsEnabled,
		&i.HighRiskStartTime,
		&i.HighRiskEndTime,
		&i.NightModeEnabled,
		&i.NightModeStartTime,
		&i.NightModeEndTime,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertAnonymousSafetySettings = `-- name: UpsertAnonymousSafetySettings :exec
INSERT INTO user_safety_settings (
    id, user_id, anonymous_session_id, device_id,
    notifications_enabled, notification_alert_types, notification_alert_radius_mins,
    notification_report_types, notification_report_radius_mins,
    location_sharing_enabled, location_history_enabled,
    profile_visibility, anonymous_reports, show_online_status,
    auto_alerts_enabled, danger_zones_enabled, time_based_alerts_enabled,
    high_risk_start_time, high_risk_end_time,
    night_mode_enabled, night_mode_start_time, night_mode_end_time,
    created_at, updated_at
)
VALUES ($1, NULL, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22, $23)
ON CONFLICT (id)
DO UPDATE SET
    user_id = EXCLUDED.user_id,
    anonymous_session_id = EXCLUDED.anonymous_session_id,
    device_id = EXCLUDED.device_id,
    notifications_enabled = EXCLUDED.notifications_enabled,
    notification_alert_types = EXCLUDED.notification_alert_types,
    notification_alert_radius_mins = EXCLUDED.notification_alert_radius_mins,
    notification_report_types = EXCLUDED.notification_report_types,
    notification_report_radius_mins = EXCLUDED.notification_report_radius_mins,
    location_sharing_enabled = EXCLUDED.location_sharing_enabled,
    location_history_enabled = EXCLUDED.location_history_enabled,
    profile_visibility = EXCLUDED.profile_visibility,
    anonymous_reports = EXCLUDED.anonymous_reports,
    show_online_status = EXCLUDED.show_online_status,
    auto_alerts_enabled = EXCLUDED.auto_alerts_enabled,
    danger_zones_enabled = EXCLUDED.danger_zones_enabled,
    time_based_alerts_enabled = EXCLUDED.time_based_alerts_enabled,
    high_risk_start_time = EXCLUDED.high_risk_start_time,
    high_risk_end_time = EXCLUDED.high_risk_end_time,
    night_mode_enabled = EXCLUDED.night_mode_enabled,
    night_mode_start_time = EXCLUDED.night_mode_start_time,
    night_mode_end_time = EXCLUDED.night_mode_end_time,
    updated_at = EXCLUDED.updated_at
`

type UpsertAnonymousSafetySettingsParams struct {
	ID                           uuid.UUID      `json:"id"`
	AnonymousSessionID           uuid.NullUUID  `json:"anonymous_session_id"`
	DeviceID                     sql.NullString `json:"device_id"`
	NotificationsEnabled         sql.NullBool   `json:"notifications_enabled"`
	NotificationAlertTypes       []string       `json:"notification_alert_types"`
	NotificationAlertRadiusMins  sql.NullInt32  `json:"notification_alert_radius_mins"`
	NotificationReportTypes      []string       `json:"notification_report_types"`
	NotificationReportRadiusMins sql.NullInt32  `json:"notification_report_radius_mins"`
	LocationSharingEnabled       sql.NullBool   `json:"location_sharing_enabled"`
	LocationHistoryEnabled       sql.NullBool   `json:"location_history_enabled"`
	ProfileVisibility            sql.NullString `json:"profile_visibility"`
	AnonymousReports             sql.NullBool   `json:"anonymous_reports"`
	ShowOnlineStatus             sql.NullBool   `json:"show_online_status"`
	AutoAlertsEnabled            sql.NullBool   `json:"auto_alerts_enabled"`
	DangerZonesEnabled           sql.NullBool   `json:"danger_zones_enabled"`
	TimeBasedAlertsEnabled       sql.NullBool   `json:"time_based_alerts_enabled"`
	HighRiskStartTime            sql.NullTime   `json:"high_risk_start_time"`
	HighRiskEndTime              sql.NullTime   `json:"high_risk_end_time"`
	NightModeEnabled             sql.NullBool   `json:"night_mode_enabled"`
	NightModeStartTime           sql.NullTime   `json:"night_mode_start_time"`
	NightModeEndTime             sql.NullTime   `json:"night_mode_end_time"`
	CreatedAt                    sql.NullTime   `json:"created_at"`
	UpdatedAt                    sql.NullTime   `json:"updated_at"`
}

func (q *Queries) UpsertAnonymousSafetySettings(ctx context.Context, arg UpsertAnonymousSafetySettingsParams) error {
	_, err := q.db.ExecContext(ctx, upsertAnonymousSafetySettings,
		arg.ID,
		arg.AnonymousSessionID,
		arg.DeviceID,
		arg.NotificationsEnabled,
		pq.Array(arg.NotificationAlertTypes),
		arg.NotificationAlertRadiusMins,
		pq.Array(arg.NotificationReportTypes),
		arg.NotificationReportRadiusMins,
		arg.LocationSharingEnabled,
		arg.LocationHistoryEnabled,
		arg.ProfileVisibility,
		arg.AnonymousReports,
		arg.ShowOnlineStatus,
		arg.AutoAlertsEnabled,
		arg.DangerZonesEnabled,
		arg.TimeBasedAlertsEnabled,
		arg.HighRiskStartTime,
		arg.HighRiskEndTime,
		arg.NightModeEnabled,
		arg.NightModeStartTime,
		arg.NightModeEndTime,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const upsertSafetySettings = `-- name: UpsertSafetySettings :exec
INSERT INTO user_safety_settings (
    id, user_id,
    notifications_enabled, notification_alert_types, notification_alert_radius_mins,
    notification_report_types, notification_report_radius_mins,
    location_sharing_enabled, location_history_enabled,
    profile_visibility, anonymous_reports, show_online_status,
    auto_alerts_enabled, danger_zones_enabled, time_based_alerts_enabled,
    high_risk_start_time, high_risk_end_time,
    night_mode_enabled, night_mode_start_time, night_mode_end_time,
    created_at, updated_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22)
ON CONFLICT (user_id)
DO UPDATE SET
    notifications_enabled = EXCLUDED.notifications_enabled,
    notification_alert_types = EXCLUDED.notification_alert_types,
    notification_alert_radius_mins = EXCLUDED.notification_alert_radius_mins,
    notification_report_types = EXCLUDED.notification_report_types,
    notification_report_radius_mins = EXCLUDED.notification_report_radius_mins,
    location_sharing_enabled = EXCLUDED.location_sharing_enabled,
    location_history_enabled = EXCLUDED.location_history_enabled,
    profile_visibility = EXCLUDED.profile_visibility,
    anonymous_reports = EXCLUDED.anonymous_reports,
    show_online_status = EXCLUDED.show_online_status,
    auto_alerts_enabled = EXCLUDED.auto_alerts_enabled,
    danger_zones_enabled = EXCLUDED.danger_zones_enabled,
    time_based_alerts_enabled = EXCLUDED.time_based_alerts_enabled,
    high_risk_start_time = EXCLUDED.high_risk_start_time,
    high_risk_end_time = EXCLUDED.high_risk_end_time,
    night_mode_enabled = EXCLUDED.night_mode_enabled,
    night_mode_start_time = EXCLUDED.night_mode_start_time,
    night_mode_end_time = EXCLUDED.night_mode_end_time,
    updated_at = EXCLUDED.updated_at
`

type UpsertSafetySettingsParams struct {
	ID                           uuid.UUID      `json:"id"`
	UserID                       uuid.NullUUID  `json:"user_id"`
	NotificationsEnabled         sql.NullBool   `json:"notifications_enabled"`
	NotificationAlertTypes       []string       `json:"notification_alert_types"`
	NotificationAlertRadiusMins  sql.NullInt32  `json:"notification_alert_radius_mins"`
	NotificationReportTypes      []string       `json:"notification_report_types"`
	NotificationReportRadiusMins sql.NullInt32  `json:"notification_report_radius_mins"`
	LocationSharingEnabled       sql.NullBool   `json:"location_sharing_enabled"`
	LocationHistoryEnabled       sql.NullBool   `json:"location_history_enabled"`
	ProfileVisibility            sql.NullString `json:"profile_visibility"`
	AnonymousReports             sql.NullBool   `json:"anonymous_reports"`
	ShowOnlineStatus             sql.NullBool   `json:"show_online_status"`
	AutoAlertsEnabled            sql.NullBool   `json:"auto_alerts_enabled"`
	DangerZonesEnabled           sql.NullBool   `json:"danger_zones_enabled"`
	TimeBasedAlertsEnabled       sql.NullBool   `json:"time_based_alerts_enabled"`
	HighRiskStartTime            sql.NullTime   `json:"high_risk_start_time"`
	HighRiskEndTime              sql.NullTime   `json:"high_risk_end_time"`
	NightModeEnabled             sql.NullBool   `json:"night_mode_enabled"`
	NightModeStartTime           sql.NullTime   `json:"night_mode_start_time"`
	NightModeEndTime             sql.NullTime   `json:"night_mode_end_time"`
	CreatedAt                    sql.NullTime   `json:"created_at"`
	UpdatedAt                    sql.NullTime   `json:"updated_at"`
}

func (q *Queries) UpsertSafetySettings(ctx context.Context, arg UpsertSafetySettingsParams) error {
	_, err := q.db.ExecContext(ctx, upsertSafetySettings,
		arg.ID,
		arg.UserID,
		arg.NotificationsEnabled,
		pq.Array(arg.NotificationAlertTypes),
		arg.NotificationAlertRadiusMins,
		pq.Array(arg.NotificationReportTypes),
		arg.NotificationReportRadiusMins,
		arg.LocationSharingEnabled,
		arg.LocationHistoryEnabled,
		arg.ProfileVisibility,
		arg.AnonymousReports,
		arg.ShowOnlineStatus,
		arg.AutoAlertsEnabled,
		arg.DangerZonesEnabled,
		arg.TimeBasedAlertsEnabled,
		arg.HighRiskStartTime,
		arg.HighRiskEndTime,
		arg.NightModeEnabled,
		arg.NightModeStartTime,
		arg.NightModeEndTime,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
