// Code generated by MockGen. DO NOT EDIT.
// Source: domain/repository/location_type.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	entities "github.com/risk-place-angola/backend-risk-place/domain/entities"
)

// MockLocationTypeRepository is a mock of LocationTypeRepository interface.
type MockLocationTypeRepository struct {
	ctrl     *gomock.Controller
	recorder *MockLocationTypeRepositoryMockRecorder
}

// MockLocationTypeRepositoryMockRecorder is the mock recorder for MockLocationTypeRepository.
type MockLocationTypeRepositoryMockRecorder struct {
	mock *MockLocationTypeRepository
}

// NewMockLocationTypeRepository creates a new mock instance.
func NewMockLocationTypeRepository(ctrl *gomock.Controller) *MockLocationTypeRepository {
	mock := &MockLocationTypeRepository{ctrl: ctrl}
	mock.recorder = &MockLocationTypeRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLocationTypeRepository) EXPECT() *MockLocationTypeRepositoryMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockLocationTypeRepository) Delete(id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockLocationTypeRepositoryMockRecorder) Delete(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockLocationTypeRepository)(nil).Delete), id)
}

// FindAll mocks base method.
func (m *MockLocationTypeRepository) FindAll() ([]*entities.LocationType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll")
	ret0, _ := ret[0].([]*entities.LocationType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockLocationTypeRepositoryMockRecorder) FindAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockLocationTypeRepository)(nil).FindAll))
}

// FindByID mocks base method.
func (m *MockLocationTypeRepository) FindByID(id string) (*entities.LocationType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", id)
	ret0, _ := ret[0].(*entities.LocationType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockLocationTypeRepositoryMockRecorder) FindByID(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockLocationTypeRepository)(nil).FindByID), id)
}

// Save mocks base method.
func (m *MockLocationTypeRepository) Save(entity *entities.LocationType) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", entity)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockLocationTypeRepositoryMockRecorder) Save(entity interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockLocationTypeRepository)(nil).Save), entity)
}

// Update mocks base method.
func (m *MockLocationTypeRepository) Update(entity *entities.LocationType) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", entity)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockLocationTypeRepositoryMockRecorder) Update(entity interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockLocationTypeRepository)(nil).Update), entity)
}
